[build]
  publish = "public"
  command = "cp public/index-netlify.html public/index.html"

[build.environment]
  NODE_VERSION = "18"

[functions]
  directory = "functions"

[[redirects]]
  from = "/api/news"
  to = "/.netlify/functions/news"
  status = 200

[[redirects]]
  from = "/api/refresh"
  to = "/.netlify/functions/refresh"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[dev]
  framework = "#static"
  port = 8888
  publish = "public"
  autoLaunch = true 